services:
  # ----------------------------------------------------
  # User Service
  # ----------------------------------------------------
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: user
    container_name: ecom-user-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 60000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 30000
    restart: unless-stopped

  # ----------------------------------------------------
  # Product Service
  # ----------------------------------------------------
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: product
    container_name: ecom-product-service
    ports:
      - "8081:8080"  # Exposed on host port 8081
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 60000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 30000
    restart: unless-stopped

  # ----------------------------------------------------
  # Order Service
  # # ----------------------------------------------------
  # order-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       SERVICE_NAME: order
  #   container_name: ecom-order-service
  #   ports:
  #     - "8082:8080"  # Exposed on host port 8082
  #   env_file:
  #     - .env
  #   environment:
  #     SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
  #     SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
  #     SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
  #     SPRING_JPA_HIBERNATE_DDL_AUTO: update
  #     SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 60000
  #     SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 30000
  #   restart: unless-stopped