spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://ep-rough-scene-zamrnv5o-pooler.c-2.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_lKGV5vuQs1Sp
  # Enable automatic schema creation/updating
  jpa:
    hibernate:
      ddl-auto: update
      # generate-ddl: true

    # Useful for debugging: prints executed SQL statements to the console
    show-sql: true

server:
  port: 8081
